# Generated by Django 5.0.1 on 2024-01-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('habitat', models.IntegerField()),
            ],
        ),
    ]
