# Generated by Django 5.0.1 on 2024-01-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='family',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='creature',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='creatures/'),
        ),
        migrations.AddField(
            model_name='creature',
            name='predators',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='creature',
            name='prey',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='creature',
            name='scientific_name',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AlterField(
            model_name='creature',
            name='diet',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='creature',
            name='habitat',
            field=models.CharField(max_length=100),
        ),
    ]
