# Generated by Django 5.0.1 on 2024-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_creature_appearance_alter_creature_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='appearance',
            field=models.CharField(default='default_value', max_length=300),
        ),
    ]
